[project]
name = "ml-service"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Mwale Jonathan", email = "mwalejonathan10@gmail.com" }
]
requires-python = ">=3.12"
dependencies = [
    "jupyterlab>=4.6.3",
    "notebook>=7.6.2",
    "pandas>=3.0.6",
]

[tool.uv]
exclude-newer = "14 days"
